version: '3'
services:
 php-fpm:
  build: .
  container_name: projetAstronomie3
  volumes:
  - ./dev:/var/www/html
  ports:
  - "8000:8000"
  environment:
    PHP_IDE_CONFIG: serverName=projetAstronomie3
 mysql:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: test2
  ports:
    - '3306:3306'
 phpmyadmin:
  depends_on:
   - mysql
  image: phpmyadmin/phpmyadmin
  restart: always
  ports:
   - '8080:80'
  environment:
   PMA_HOST: mysql
