<?php

namespace ContainerW5QocT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QKjGvyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q_KjGvy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q_KjGvy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'messierCatalogue' => ['privates', '.errored..service_locator.Q_KjGvy.App\\Entity\\MessierCatalogue', NULL, 'Cannot autowire service ".service_locator.Q_KjGvy": it references class "App\\Entity\\MessierCatalogue" but no such service exists.'],
            'messierCatalogueRepository' => ['privates', 'App\\Repository\\MessierCatalogueRepository', 'getMessierCatalogueRepositoryService', true],
        ], [
            'messierCatalogue' => 'App\\Entity\\MessierCatalogue',
            'messierCatalogueRepository' => 'App\\Repository\\MessierCatalogueRepository',
        ]);
    }
}
