<?php

namespace ContainerW5QocT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7urbllZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7urbllZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7urbllZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'objetCeleste' => ['privates', '.errored..service_locator.7urbllZ.App\\Entity\\ObjetCeleste', NULL, 'Cannot autowire service ".service_locator.7urbllZ": it references class "App\\Entity\\ObjetCeleste" but no such service exists.'],
        ], [
            'objetCeleste' => 'App\\Entity\\ObjetCeleste',
        ]);
    }
}
