<?php

namespace ContainerW5QocT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NHv40cZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nHv40cZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nHv40cZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'constellation' => ['privates', '.errored..service_locator.nHv40cZ.App\\Entity\\Constellation', NULL, 'Cannot autowire service ".service_locator.nHv40cZ": it references class "App\\Entity\\Constellation" but no such service exists.'],
        ], [
            'constellation' => 'App\\Entity\\Constellation',
        ]);
    }
}
