<?php

namespace ContainerW5QocT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessierCatalogue2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jlmOxZG.App\Entity\MessierCatalogue' shared service.
     *
     * @return \App\Entity\MessierCatalogue
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jlmOxZG": it references class "App\\Entity\\MessierCatalogue" but no such service exists.');
    }
}
