<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Constellation extends \App\Entity\Constellation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Observation_Season', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Code_Constellation', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Latin_name', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'French_name', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'English_name', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'area_in_square_degrees', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Dec_Declinaison', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'RA_Right_Ascension', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Principal_star', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'area_celestial_sphere', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'zone_celestial_equator', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'zone_ecliptic', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'zone_Milky_Way', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Quad', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Name_origin', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Pictures', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'yes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Observation_Season', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Code_Constellation', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Latin_name', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'French_name', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'English_name', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'area_in_square_degrees', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Dec_Declinaison', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'RA_Right_Ascension', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Principal_star', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'area_celestial_sphere', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'zone_celestial_equator', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'zone_ecliptic', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'zone_Milky_Way', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Quad', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Name_origin', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'Pictures', '' . "\0" . 'App\\Entity\\Constellation' . "\0" . 'yes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Constellation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getObservationSeason(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservationSeason', []);

        return parent::getObservationSeason();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservationSeason(?string $Observation_Season): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservationSeason', [$Observation_Season]);

        return parent::setObservationSeason($Observation_Season);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeConstellation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeConstellation', []);

        return parent::getCodeConstellation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeConstellation(string $Code_Constellation): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeConstellation', [$Code_Constellation]);

        return parent::setCodeConstellation($Code_Constellation);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatinName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatinName', []);

        return parent::getLatinName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatinName(?string $Latin_name): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatinName', [$Latin_name]);

        return parent::setLatinName($Latin_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrenchName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrenchName', []);

        return parent::getFrenchName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrenchName(?string $French_name): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrenchName', [$French_name]);

        return parent::setFrenchName($French_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnglishName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnglishName', []);

        return parent::getEnglishName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnglishName(?string $English_name): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnglishName', [$English_name]);

        return parent::setEnglishName($English_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaInSquareDegrees(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaInSquareDegrees', []);

        return parent::getAreaInSquareDegrees();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaInSquareDegrees(?string $area_in_square_degrees): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaInSquareDegrees', [$area_in_square_degrees]);

        return parent::setAreaInSquareDegrees($area_in_square_degrees);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecDeclinaison(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecDeclinaison', []);

        return parent::getDecDeclinaison();
    }

    /**
     * {@inheritDoc}
     */
    public function setDecDeclinaison(?string $Dec_Declinaison): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDecDeclinaison', [$Dec_Declinaison]);

        return parent::setDecDeclinaison($Dec_Declinaison);
    }

    /**
     * {@inheritDoc}
     */
    public function getRARightAscension(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRARightAscension', []);

        return parent::getRARightAscension();
    }

    /**
     * {@inheritDoc}
     */
    public function setRARightAscension(?string $RA_Right_Ascension): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRARightAscension', [$RA_Right_Ascension]);

        return parent::setRARightAscension($RA_Right_Ascension);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrincipalStar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrincipalStar', []);

        return parent::getPrincipalStar();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrincipalStar(?string $Principal_star): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrincipalStar', [$Principal_star]);

        return parent::setPrincipalStar($Principal_star);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaCelestialSphere(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaCelestialSphere', []);

        return parent::getAreaCelestialSphere();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaCelestialSphere(?string $area_celestial_sphere): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaCelestialSphere', [$area_celestial_sphere]);

        return parent::setAreaCelestialSphere($area_celestial_sphere);
    }

    /**
     * {@inheritDoc}
     */
    public function getZoneCelestialEquator(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZoneCelestialEquator', []);

        return parent::getZoneCelestialEquator();
    }

    /**
     * {@inheritDoc}
     */
    public function setZoneCelestialEquator(?string $zone_celestial_equator): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZoneCelestialEquator', [$zone_celestial_equator]);

        return parent::setZoneCelestialEquator($zone_celestial_equator);
    }

    /**
     * {@inheritDoc}
     */
    public function getZoneEcliptic(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZoneEcliptic', []);

        return parent::getZoneEcliptic();
    }

    /**
     * {@inheritDoc}
     */
    public function setZoneEcliptic(?string $zone_ecliptic): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZoneEcliptic', [$zone_ecliptic]);

        return parent::setZoneEcliptic($zone_ecliptic);
    }

    /**
     * {@inheritDoc}
     */
    public function getZoneMilkyWay(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZoneMilkyWay', []);

        return parent::getZoneMilkyWay();
    }

    /**
     * {@inheritDoc}
     */
    public function setZoneMilkyWay(?string $zone_Milky_Way): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZoneMilkyWay', [$zone_Milky_Way]);

        return parent::setZoneMilkyWay($zone_Milky_Way);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuad(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuad', []);

        return parent::getQuad();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuad(?string $Quad): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuad', [$Quad]);

        return parent::setQuad($Quad);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameOrigin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameOrigin', []);

        return parent::getNameOrigin();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameOrigin(?string $Name_origin): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameOrigin', [$Name_origin]);

        return parent::setNameOrigin($Name_origin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPictures(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPictures', []);

        return parent::getPictures();
    }

    /**
     * {@inheritDoc}
     */
    public function setPictures(?string $Pictures): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPictures', [$Pictures]);

        return parent::setPictures($Pictures);
    }

    /**
     * {@inheritDoc}
     */
    public function getYes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYes', []);

        return parent::getYes();
    }

    /**
     * {@inheritDoc}
     */
    public function addYe(\App\Entity\ObjetCeleste $ye): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addYe', [$ye]);

        return parent::addYe($ye);
    }

    /**
     * {@inheritDoc}
     */
    public function removeYe(\App\Entity\ObjetCeleste $ye): \App\Entity\Constellation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeYe', [$ye]);

        return parent::removeYe($ye);
    }

}
