<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MessierCatalogue extends \App\Entity\MessierCatalogue implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Messier', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'NGC', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Object_type', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Season', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Magnitude', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Constellation_EN', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Constellation_FR', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Constellation_Latin', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'RA_Right_Ascension', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Dec_Declinaison', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Distance_ly_a_l', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Size_Dimension', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Discoverer', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Year_Annee', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Pictures', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'URL_de_limage', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Constellation', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'yes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Messier', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'NGC', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Object_type', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Season', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Magnitude', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Constellation_EN', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Constellation_FR', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Constellation_Latin', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'RA_Right_Ascension', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Dec_Declinaison', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Distance_ly_a_l', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Size_Dimension', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Discoverer', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Year_Annee', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Pictures', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'URL_de_limage', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'Constellation', '' . "\0" . 'App\\Entity\\MessierCatalogue' . "\0" . 'yes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MessierCatalogue $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMessier(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessier', []);

        return parent::getMessier();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessier(string $Messier): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessier', [$Messier]);

        return parent::setMessier($Messier);
    }

    /**
     * {@inheritDoc}
     */
    public function getNGC(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNGC', []);

        return parent::getNGC();
    }

    /**
     * {@inheritDoc}
     */
    public function setNGC(?string $NGC): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNGC', [$NGC]);

        return parent::setNGC($NGC);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectType', []);

        return parent::getObjectType();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjectType(?string $Object_type): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjectType', [$Object_type]);

        return parent::setObjectType($Object_type);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeason(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeason', []);

        return parent::getSeason();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeason(?string $Season): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeason', [$Season]);

        return parent::setSeason($Season);
    }

    /**
     * {@inheritDoc}
     */
    public function getMagnitude(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMagnitude', []);

        return parent::getMagnitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setMagnitude(?int $Magnitude): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMagnitude', [$Magnitude]);

        return parent::setMagnitude($Magnitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstellationEN(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstellationEN', []);

        return parent::getConstellationEN();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstellationEN(?string $Constellation_EN): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstellationEN', [$Constellation_EN]);

        return parent::setConstellationEN($Constellation_EN);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstellationFR(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstellationFR', []);

        return parent::getConstellationFR();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstellationFR(?string $Constellation_FR): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstellationFR', [$Constellation_FR]);

        return parent::setConstellationFR($Constellation_FR);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstellationLatin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstellationLatin', []);

        return parent::getConstellationLatin();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstellationLatin(?string $Constellation_Latin): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstellationLatin', [$Constellation_Latin]);

        return parent::setConstellationLatin($Constellation_Latin);
    }

    /**
     * {@inheritDoc}
     */
    public function getRARightAscension(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRARightAscension', []);

        return parent::getRARightAscension();
    }

    /**
     * {@inheritDoc}
     */
    public function setRARightAscension(?string $RA_Right_Ascension): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRARightAscension', [$RA_Right_Ascension]);

        return parent::setRARightAscension($RA_Right_Ascension);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecDeclinaison(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecDeclinaison', []);

        return parent::getDecDeclinaison();
    }

    /**
     * {@inheritDoc}
     */
    public function setDecDeclinaison(?string $Dec_Declinaison): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDecDeclinaison', [$Dec_Declinaison]);

        return parent::setDecDeclinaison($Dec_Declinaison);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistanceLyAL(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistanceLyAL', []);

        return parent::getDistanceLyAL();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistanceLyAL(?int $Distance_ly_a_l): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistanceLyAL', [$Distance_ly_a_l]);

        return parent::setDistanceLyAL($Distance_ly_a_l);
    }

    /**
     * {@inheritDoc}
     */
    public function getSizeDimension(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSizeDimension', []);

        return parent::getSizeDimension();
    }

    /**
     * {@inheritDoc}
     */
    public function setSizeDimension(?string $Size_Dimension): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSizeDimension', [$Size_Dimension]);

        return parent::setSizeDimension($Size_Dimension);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscoverer(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscoverer', []);

        return parent::getDiscoverer();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscoverer(?string $Discoverer): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscoverer', [$Discoverer]);

        return parent::setDiscoverer($Discoverer);
    }

    /**
     * {@inheritDoc}
     */
    public function getYearAnnee(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYearAnnee', []);

        return parent::getYearAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setYearAnnee(?int $Year_Annee): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYearAnnee', [$Year_Annee]);

        return parent::setYearAnnee($Year_Annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getPictures(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPictures', []);

        return parent::getPictures();
    }

    /**
     * {@inheritDoc}
     */
    public function setPictures(?string $Pictures): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPictures', [$Pictures]);

        return parent::setPictures($Pictures);
    }

    /**
     * {@inheritDoc}
     */
    public function getURLDeLimage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getURLDeLimage', []);

        return parent::getURLDeLimage();
    }

    /**
     * {@inheritDoc}
     */
    public function setURLDeLimage(?string $URL_de_limage): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setURLDeLimage', [$URL_de_limage]);

        return parent::setURLDeLimage($URL_de_limage);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstellation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstellation', []);

        return parent::getConstellation();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstellation(?string $Constellation): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstellation', [$Constellation]);

        return parent::setConstellation($Constellation);
    }

    /**
     * {@inheritDoc}
     */
    public function getYes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYes', []);

        return parent::getYes();
    }

    /**
     * {@inheritDoc}
     */
    public function addYe(\App\Entity\ObjetCeleste $ye): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addYe', [$ye]);

        return parent::addYe($ye);
    }

    /**
     * {@inheritDoc}
     */
    public function removeYe(\App\Entity\ObjetCeleste $ye): \App\Entity\MessierCatalogue
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeYe', [$ye]);

        return parent::removeYe($ye);
    }

}
