<?php

namespace ContainerFv7U34S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HeeCtdIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HeeCtdI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HeeCtdI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ConstellationController::delete' => ['privates', '.service_locator.DJyAtOr', 'get_ServiceLocator_DJyAtOrService', true],
            'App\\Controller\\ConstellationController::edit' => ['privates', '.service_locator.DJyAtOr', 'get_ServiceLocator_DJyAtOrService', true],
            'App\\Controller\\ConstellationController::index' => ['privates', '.service_locator.AXr93Kl', 'get_ServiceLocator_AXr93KlService', true],
            'App\\Controller\\ConstellationController::new' => ['privates', '.service_locator.AXr93Kl', 'get_ServiceLocator_AXr93KlService', true],
            'App\\Controller\\ConstellationController::show' => ['privates', '.service_locator.nHv40cZ', 'get_ServiceLocator_NHv40cZService', true],
            'App\\Controller\\MessierCatalogueController::delete' => ['privates', '.service_locator.Q_KjGvy', 'get_ServiceLocator_QKjGvyService', true],
            'App\\Controller\\MessierCatalogueController::edit' => ['privates', '.service_locator.Q_KjGvy', 'get_ServiceLocator_QKjGvyService', true],
            'App\\Controller\\MessierCatalogueController::index' => ['privates', '.service_locator.VyeK47G', 'get_ServiceLocator_VyeK47GService', true],
            'App\\Controller\\MessierCatalogueController::new' => ['privates', '.service_locator.VyeK47G', 'get_ServiceLocator_VyeK47GService', true],
            'App\\Controller\\MessierCatalogueController::show' => ['privates', '.service_locator.jlmOxZG', 'get_ServiceLocator_JlmOxZGService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\ConstellationController:delete' => ['privates', '.service_locator.DJyAtOr', 'get_ServiceLocator_DJyAtOrService', true],
            'App\\Controller\\ConstellationController:edit' => ['privates', '.service_locator.DJyAtOr', 'get_ServiceLocator_DJyAtOrService', true],
            'App\\Controller\\ConstellationController:index' => ['privates', '.service_locator.AXr93Kl', 'get_ServiceLocator_AXr93KlService', true],
            'App\\Controller\\ConstellationController:new' => ['privates', '.service_locator.AXr93Kl', 'get_ServiceLocator_AXr93KlService', true],
            'App\\Controller\\ConstellationController:show' => ['privates', '.service_locator.nHv40cZ', 'get_ServiceLocator_NHv40cZService', true],
            'App\\Controller\\MessierCatalogueController:delete' => ['privates', '.service_locator.Q_KjGvy', 'get_ServiceLocator_QKjGvyService', true],
            'App\\Controller\\MessierCatalogueController:edit' => ['privates', '.service_locator.Q_KjGvy', 'get_ServiceLocator_QKjGvyService', true],
            'App\\Controller\\MessierCatalogueController:index' => ['privates', '.service_locator.VyeK47G', 'get_ServiceLocator_VyeK47GService', true],
            'App\\Controller\\MessierCatalogueController:new' => ['privates', '.service_locator.VyeK47G', 'get_ServiceLocator_VyeK47GService', true],
            'App\\Controller\\MessierCatalogueController:show' => ['privates', '.service_locator.jlmOxZG', 'get_ServiceLocator_JlmOxZGService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\ConstellationController::delete' => '?',
            'App\\Controller\\ConstellationController::edit' => '?',
            'App\\Controller\\ConstellationController::index' => '?',
            'App\\Controller\\ConstellationController::new' => '?',
            'App\\Controller\\ConstellationController::show' => '?',
            'App\\Controller\\MessierCatalogueController::delete' => '?',
            'App\\Controller\\MessierCatalogueController::edit' => '?',
            'App\\Controller\\MessierCatalogueController::index' => '?',
            'App\\Controller\\MessierCatalogueController::new' => '?',
            'App\\Controller\\MessierCatalogueController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ConstellationController:delete' => '?',
            'App\\Controller\\ConstellationController:edit' => '?',
            'App\\Controller\\ConstellationController:index' => '?',
            'App\\Controller\\ConstellationController:new' => '?',
            'App\\Controller\\ConstellationController:show' => '?',
            'App\\Controller\\MessierCatalogueController:delete' => '?',
            'App\\Controller\\MessierCatalogueController:edit' => '?',
            'App\\Controller\\MessierCatalogueController:index' => '?',
            'App\\Controller\\MessierCatalogueController:new' => '?',
            'App\\Controller\\MessierCatalogueController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
