<?php

namespace ContainerFv7U34S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DJyAtOrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DJyAtOr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DJyAtOr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'constellation' => ['privates', '.errored..service_locator.DJyAtOr.App\\Entity\\Constellation', NULL, 'Cannot autowire service ".service_locator.DJyAtOr": it references class "App\\Entity\\Constellation" but no such service exists.'],
            'constellationRepository' => ['privates', 'App\\Repository\\ConstellationRepository', 'getConstellationRepositoryService', true],
        ], [
            'constellation' => 'App\\Entity\\Constellation',
            'constellationRepository' => 'App\\Repository\\ConstellationRepository',
        ]);
    }
}
