<?php

namespace ContainerFv7U34S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConstellation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nHv40cZ.App\Entity\Constellation' shared service.
     *
     * @return \App\Entity\Constellation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nHv40cZ": it references class "App\\Entity\\Constellation" but no such service exists.');
    }
}
