<?php

namespace ContainerILxeeNt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AXr93KlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AXr93Kl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AXr93Kl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'constellationRepository' => ['privates', 'App\\Repository\\ConstellationRepository', 'getConstellationRepositoryService', true],
        ], [
            'constellationRepository' => 'App\\Repository\\ConstellationRepository',
        ]);
    }
}
