<?php

namespace ContainerILxeeNt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JlmOxZGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jlmOxZG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jlmOxZG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'messierCatalogue' => ['privates', '.errored..service_locator.jlmOxZG.App\\Entity\\MessierCatalogue', NULL, 'Cannot autowire service ".service_locator.jlmOxZG": it references class "App\\Entity\\MessierCatalogue" but no such service exists.'],
        ], [
            'messierCatalogue' => 'App\\Entity\\MessierCatalogue',
        ]);
    }
}
