<?php

namespace ContainerILxeeNt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O2OoXOGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o2OoXOG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o2OoXOG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'objetCelesteRepository' => ['privates', 'App\\Repository\\ObjetCelesteRepository', 'getObjetCelesteRepositoryService', true],
        ], [
            'objetCelesteRepository' => 'App\\Repository\\ObjetCelesteRepository',
        ]);
    }
}
