<?php

namespace ContainerILxeeNt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjetCeleste2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HH85IY3.App\Entity\ObjetCeleste' shared service.
     *
     * @return \App\Entity\ObjetCeleste
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.HH85IY3": it references class "App\\Entity\\ObjetCeleste" but no such service exists.');
    }
}
